services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - library_sql_data:/var/opt/mssql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "if [ -x /opt/mssql-tools18/bin/sqlcmd ]; then /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q \"SELECT 1\"; else /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -Q \"SELECT 1\"; fi"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  api:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"

      ConnectionStrings__LibraryDb: "Server=sqlserver,1433;Database=LibraryDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};Encrypt=True;TrustServerCertificate=True"

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__RefreshTokenDays: "7"

    ports:
      - "8080:8080"

    depends_on:
      sqlserver:
        condition: service_healthy


volumes:
  library_sql_data: